openapi: "3.0.1"
info:
  title: Gravitate Health Focusing Service API Interface
  version: MVP2
  description: Gravitate Health Focusing Service. Focuses a Focused ePI.
  contact: {}
servers:
  - url: https://fosps.gravitatehealth.eu
paths:
  /lenses:
    get:
      tags:
        - Lenses
      description: Returns all lenses IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  lenses:
                    type: array
                    items:
                      type: string
                    example: ["lense1", "lense2", "lense3"]

  /lenses/{id}:
    get:
      tags:
        - Lenses
      description: Returns the lense itself.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                  lense:
                    type: string
                    example: "console.log('Hello World!')"

